### PR TITLE
Gameshark Codes for research

### PR DESCRIPTION
**Pull request by Lucoshi**

### CODE REVIEW

**Comment by mkst** [comment]
Hey @Lucoshi  thank you for your contribution, but I think these files would be better suited to the Wiki section of this project, rather than being checked into the codebase.

**Comment by Lucoshi** [comment]
So why you don't you do it?

**Comment by mkst** [comment]
Because I have other things going on in my life than this project 😅

**Comment by mkst** [comment]
Done - https://github.com/mkst/conker/wiki/Research. Closing this ticket. Thanks!

**Pull request closed without merging**
